[package]
name = "ggml"
description = "GGML tensor library for Rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gguf = { workspace = true }
bytemuck = { workspace = true }
half = { workspace = true }
tracing = { workspace = true }
bumpalo = { workspace = true, features = ["boxed"] }

[dev-dependencies]
criterion = { workspace = true }
